require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - 'lib/review_app_seeder.rb'
  - 'db/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'
  - 'bin/**/*'
  - 'log/**/*'
  - 'spec/support/materialize_select_helper.rb'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: false

LetSetup:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
  - 'config/routes.rb'
  - 'config/environments/production.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
  - 'spec/rails_helper.rb'
  - 'config/initializers/*'

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false


Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
